# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "406624b864e23c167e8e18e8b7f5c6d2"
name = "GSAN Portal"
handle = "gsan-portal"
application_url = "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,unauthenticated_read_customers"

[auth]
redirect_urls = [
  "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/",
  "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/app",
  "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/auth",
  "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/auth/callback",
  "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/gsan/login"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://d6c8-2604-3d08-4e82-a500-81f4-333b-5911-531b.ngrok-free.app/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "gsan-test.myshopify.com"
automatically_update_urls_on_dev = false
include_config_on_deploy = true
